In [1]:
import pandas as pd
caminho_arquivo = '/content/TABELA_BRASIL_bagunçada.csv'
df = pd.read_csv(caminho_arquivo)
df.head()

,Região,UF,IBGE,Município,População,Domicílios com a TRIA aplicada,Domicílios em risco de insegurança alimentar,% Domicílios em risco de insegurança alimentar,Pessoas em domicílios em risco de insegurança alimentar,Domicílios em risco de insegurança alimentar com pessoas com deficiência,...,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado pardo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,Competência
0,NORTE,RO,110001.0,ALTA FLORESTA D'OESTE,22853.0,4218.0,24.0,0.6,78.0,5.0,...,68.4,4.0,21.1,1.0,5.3,1.0,5.3,0.0,0.0,nov/2023 a dez/2025
1,NORTE,RO,110002.0,ARIQUEMES,108573.0,26074.0,42.0,0.2,169.0,10.0,...,45.5,5.0,45.5,1.0,9.1,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
2,NORTE,RO,110003.0,CABIXI,5690.0,2359.0,5.0,0.2,12.0,0.0,...,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
3,NORTE,RO,110004.0,CACOAL,97637.0,12618.0,202.0,1.6,610.0,36.0,...,64.1,48.0,26.1,10.0,5.4,8.0,4.3,0.0,0.0,nov/2023 a dez/2025
4,NORTE,RO,110005.0,CEREJEIRAS,16975.0,11078.0,31.0,0.3,104.0,2.0,...,50.0,4.0,25.0,1.0,6.2,3.0,18.8,0.0,0.0,nov/2023 a dez/2025

In [17]:
df = df.drop_duplicates()
df

,Região,UF,IBGE,Município,População,Domicílios com a TRIA aplicada,Domicílios em risco de insegurança alimentar,% Domicílios em risco de insegurança alimentar,Pessoas em domicílios em risco de insegurança alimentar,Domicílios em risco de insegurança alimentar com pessoas com deficiência,...,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado pardo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,Competência
0,NORTE,RO,110001.0,ALTA FLORESTA D'OESTE,22853.0,4218.0,24.0,0.6,78.0,5.0,...,68.4,4.0,21.1,1.0,5.3,1.0,5.3,0.0,0.0,nov/2023 a dez/2025
1,NORTE,RO,110002.0,ARIQUEMES,108573.0,26074.0,42.0,0.2,169.0,10.0,...,45.5,5.0,45.5,1.0,9.1,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
2,NORTE,RO,110003.0,CABIXI,5690.0,2359.0,5.0,0.2,12.0,0.0,...,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
3,NORTE,RO,110004.0,CACOAL,97637.0,12618.0,202.0,1.6,610.0,36.0,...,64.1,48.0,26.1,10.0,5.4,8.0,4.3,0.0,0.0,nov/2023 a dez/2025
4,NORTE,RO,110005.0,CEREJEIRAS,16975.0,11078.0,31.0,0.3,104.0,2.0,...,50.0,4.0,25.0,1.0,6.2,3.0,18.8,0.0,0.0,nov/2023 a dez/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,CENTRO-OESTE,GO,522200.0,VIANOPOLIS,15476.0,2963.0,95.0,3.2,313.0,18.0,...,66.7,20.0,23.0,2.0,2.3,7.0,8.1,0.0,0.0,nov/2023 a dez/2025
5567,CENTRO-OESTE,GO,522205.0,VICENTINOPOLIS,9077.0,1500.0,63.0,4.2,213.0,8.0,...,80.7,6.0,10.5,4.0,7.0,1.0,1.8,0.0,0.0,nov/2023 a dez/2025
5568,CENTRO-OESTE,GO,522220.0,VILA BOA,4185.0,1398.0,58.0,4.1,213.0,9.0,...,70.8,6.0,12.5,1.0,2.1,7.0,14.6,0.0,0.0,nov/2023 a dez/2025
5569,CENTRO-OESTE,GO,522230.0,VILA PROPICIO,5982.0,83.0,1.0,1.2,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
5570,CENTRO-OESTE,DF,530010.0,BRASILIA,2982818.0,186826.0,8947.0,4.8,30750.0,1341.0,...,64.4,1704.0,20.7,362.0,4.4,859.0,10.4,6.0,0.1,nov/2023 a dez/2025

In [18]:
df = df.dropna()
df

,Região,UF,IBGE,Município,População,Domicílios com a TRIA aplicada,Domicílios em risco de insegurança alimentar,% Domicílios em risco de insegurança alimentar,Pessoas em domicílios em risco de insegurança alimentar,Domicílios em risco de insegurança alimentar com pessoas com deficiência,...,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado pardo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado branco,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado amarelo,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado preto,Domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,% de domicílios em risco de insegurança alimentar com RF respondente autodeclarado indígena,Competência
0,NORTE,RO,110001.0,ALTA FLORESTA D'OESTE,22853.0,4218.0,24.0,0.6,78.0,5.0,...,68.4,4.0,21.1,1.0,5.3,1.0,5.3,0.0,0.0,nov/2023 a dez/2025
1,NORTE,RO,110002.0,ARIQUEMES,108573.0,26074.0,42.0,0.2,169.0,10.0,...,45.5,5.0,45.5,1.0,9.1,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
2,NORTE,RO,110003.0,CABIXI,5690.0,2359.0,5.0,0.2,12.0,0.0,...,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
3,NORTE,RO,110004.0,CACOAL,97637.0,12618.0,202.0,1.6,610.0,36.0,...,64.1,48.0,26.1,10.0,5.4,8.0,4.3,0.0,0.0,nov/2023 a dez/2025
4,NORTE,RO,110005.0,CEREJEIRAS,16975.0,11078.0,31.0,0.3,104.0,2.0,...,50.0,4.0,25.0,1.0,6.2,3.0,18.8,0.0,0.0,nov/2023 a dez/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5566,CENTRO-OESTE,GO,522200.0,VIANOPOLIS,15476.0,2963.0,95.0,3.2,313.0,18.0,...,66.7,20.0,23.0,2.0,2.3,7.0,8.1,0.0,0.0,nov/2023 a dez/2025
5567,CENTRO-OESTE,GO,522205.0,VICENTINOPOLIS,9077.0,1500.0,63.0,4.2,213.0,8.0,...,80.7,6.0,10.5,4.0,7.0,1.0,1.8,0.0,0.0,nov/2023 a dez/2025
5568,CENTRO-OESTE,GO,522220.0,VILA BOA,4185.0,1398.0,58.0,4.1,213.0,9.0,...,70.8,6.0,12.5,1.0,2.1,7.0,14.6,0.0,0.0,nov/2023 a dez/2025
5569,CENTRO-OESTE,GO,522230.0,VILA PROPICIO,5982.0,83.0,1.0,1.2,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,nov/2023 a dez/2025
5570,CENTRO-OESTE,DF,530010.0,BRASILIA,2982818.0,186826.0,8947.0,4.8,30750.0,1341.0,...,64.4,1704.0,20.7,362.0,4.4,859.0,10.4,6.0,0.1,nov/2023 a dez/2025

In [10]:
colunas_texto = ['Região', 'UF', 'Município']
for col in colunas_texto:
 if col in df.columns:
  df[col] = df[col].astype(str).str.strip()
  df[col] = df[col].astype(str).str.replace(r'\s+', ' ', regex=True)

In [11]:
colunas_texto = ['Região', 'UF', 'Município']
for col in colunas_texto:
 if col in df.columns:
  df[col] = df[col].astype(str).str.upper()